package Almacen::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Almacen::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=almacen',
        user => '',
        password => '',
    }
);

=head1 NAME

Almacen::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Almacen>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Almacen::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

José Angel Leyva Portilla

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
